apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: coldyy
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@db:5432/mydatabase"
  SECRET_KEY: "coldyy-secret-key-change-this-in-production"
  SMTP_PASS: "eubqbyavelyfoakg"
  POSTGRES_PASSWORD: "password"
